# Route /deploy (and /deploy/anything) to the PHP script
Alias /autodeploy /home/phanx/autodeploy
<FilesMatch "\.(env|log|sh)$">
    Require all denied
</FilesMatch>
<Directory /home/phanx/autodeploy>
    DirectoryIndex index.php
    Options -Indexes
    AllowOverride None
    Require all granted
</Directory>
