# Route /deploy to the PHP script
Alias /autodeploy /srv/data/autodeploy

<Directory /srv/data/autodeploy>
    DirectoryIndex index.php
    Options -Indexes
    AllowOverride None
    Require all granted

    # Block .env*, .log, .sh, .json (only in this directory)
    <FilesMatch "(^\.env|\.env\..+$|\.(log|sh|json)$)">
        Require all denied
    </FilesMatch>

    # Block any subroute
    <DirectoryMatch "^/srv/data/autodeploy/.+">
        Require all denied
    </DirectoryMatch>
</Directory>
