# Route /deploy to the PHP script
Alias /autodeploy /srv/data/autodeploy

# Block .env*, .log, .sh, .json (only in /autodeploy)
<Directory /srv/data/autodeploy>
    DirectoryIndex index.php
    Options -Indexes
    AllowOverride None
    Require all granted

    <FilesMatch "(^\.env|\.env\..+$|\.(log|sh|json)$)">
        Require all denied
    </FilesMatch>
</Directory>

# Block any subroute of /autodeploy
<DirectoryMatch "^/srv/data/autodeploy/.+">
    Require all denied
</DirectoryMatch>
